name: costume_yourself_api
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - aiohttp==3.10.10
  - aiosignal==1.3.1
  - annotated-types==0.7.0
  - anyio==4.6.0
  - async-timeout==4.0.3
  - attrs==24.2.0
  - blinker==1.8.2
  - certifi==2024.8.30
  - cffi==1.17.1
  - charset-normalizer==3.4.0
  - click==8.1.7
  - colorama==0.4.6
  - exceptiongroup==1.2.2
  - flask==2.3.2
  - flask-cors==5.0.0
  - frozenlist==1.4.1
  - gevent==24.10.2
  - greenlet==3.1.1
  - h11==0.14.0
  - httpcore==1.0.6
  - httpx==0.27.2
  - idna==3.10
  - iniconfig==2.0.0
  - itsdangerous==2.2.0
  - jinja2==3.1.4
  - jsonpatch==1.33
  - jsonpointer==3.0.0
  - langchain==0.3.3
  - langchain-core==0.3.10
  - langchain-text-splitters==0.3.0
  - MarkupSafe==3.0.1
  - multidict==6.1.0
  - numpy==1.26.4
  - orjson==3.10.7
  - packaging==24.1
  - pluggy==1.5.0
  - propcache==0.2.0
  - pycparser==2.22
  - pydantic==2.9.2
  - pyjwt==2.9.0
  - pytest==7.3.1
  - python-dateutil==2.9.0.post0
  - python-decouple==3.8
  - python-dotenv==1.0.0
  - pytz==2023.3
  - pyyaml==6.0.2
  - requests==2.32.3
  - requests-toolbelt==1.0.0
  - six==1.16.0
  - sniffio==1.3.1
  - sqlalchemy==2.0.35
  - tenacity==8.5.0
  - tomli==2.0.2
  - typing-extensions==4.12.2
  - urllib3==2.2.3
  - websocket-client==1.8.0
  - yarl==1.14.0
  - zope.event==5.0
  - zope.interface==7.1.0
  - pip:
    - langsmith==0.1.134
    - ibm-watson==8.1.0
    - gunicorn==23.0.0
    - cloudinary==1.41.0
    - pydantic_core==2.23.4
